export const imageSize =[
    [
      { content: "29x29", selected: false },
      { content: "40x40", selected: false },
      { content: "57x57", selected: false },
      { content: "58x58", selected: false },
      { content: "60x60", selected: false },
      { content: "80x80", selected: false },
      { content: "87x87", selected: false },
      { content: "114x114", selected: false },
      { content: "120x120", selected: false },
      { content: "180x180", selected: false },
      { content: "1024x1024", selected: false },
    ],
    [
      { content: "20x20", selected: false },
      { content: "29x29", selected: false },
      { content: "40x40", selected: false },
      { content: "50x50", selected: false },
      { content: "58x58", selected: false },
      { content: "72x72", selected: false },
      { content: "76x76", selected: false },
      { content: "80x80", selected: false },
      { content: "100x100", selected: false },
      { content: "144x144", selected: false },
      { content: "152x152", selected: false },
      { content: "167x167", selected: false },
    ],
    [
      { content: "16x16", selected: false },
      { content: "32x32", selected: false },
      { content: "64x64", selected: false },
      { content: "128x128", selected: false },
      { content: "256x256", selected: false },
      { content: "512x512", selected: false },
      { content: "1024x1204", selected: false },
    ],
    [
      { content: "48x48", selected: false },
      { content: "55x55", selected: false },
      { content: "58x58", selected: false },
      { content: "66x66", selected: false },
      { content: "80x80", selected: false },
      { content: "87x87", selected: false },
      { content: "88x88", selected: false },
      { content: "92x92", selected: false },
      { content: "100x100", selected: false },
      { content: "102x102", selected: false },
      { content: "172x172", selected: false },
      { content: "196x196", selected: false },
      { content: "216x216", selected: false },
      { content: "1024x1024", selected: false },
    ],
    [
      { content: "48x48", selected: false },
      { content: "72x72", selected: false },
      { content: "96x96", selected: false },
      { content: "144x144", selected: false },
      { content: "192x192", selected: false },
    ],
  ]

  export const sideBarData = [
    { name: "EXIF提取器", path: "/home/extension/exif-extractor" },
    { name: "证件照编辑器", path: "/home/extension/passport-photo-editor" },
    { name: "图片EXIF提取器", path: "/home/extension/image-exif-extractor" },
    { name: "颜色提取器", path: "/home/extension/color-extractor" },
    { name: "图片转图标", path: "/home/extension/image-to-icon" },
    {
      name: "图片分享/托管/图床",
      path: "/home/extension/image-sharing-hosting",
    },
    { name: "图片调整大小", path: "/home/extension/image-resize" },
    {
      name: "设备图片生成器",
      path: "/home/extension/device-image-generator",
    },
    {
      name: "图像裁剪/翻转/旋转",
      path: "/home/extension/image-crop-flip-rotate",
    },
    { name: "Mermaid 编辑器", path: "/home/extension/mermaid-editor" },
    { name: "图片比较器", path: "/home/extension/image-comparator" },
    { name: "图片压缩器", path: "/home/extension/image-compressor" },
    { name: "图片 EXIF 编辑器", path: "/home/extension/image-exif-editor" },
    { name: "图片添加水印", path: "/home/extension/image-watermarking" },
    { name: "占位图片", path: "/home/extension/placeholder-image" },
    { name: "Favicon生成器", path: "/home/extension/favicon-generator" },
    { name: "图像背景消除", path: "/home/extension/background-removal" },
    { name: "OCR文本识别", path: "/home/extension/ocr-text-recognition" },
    { name: "图像格式转换", path: "/home/extension/image-format-conversion" },
    { name: "PlantUML 编辑器", path: "/home/extension/plantuml-editor" },
    { name: "代码转图片", path: "/home/extension/code-to-image" },
  ];